# Site settings
title: Portfolio of Brandonlee Santos
author:
  name: Brandonlee Santos
  email: santos.brandonlee1@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This site is under constant heavy construction
# Build settings
remote_theme: jekyll/minima
